In [9]:
import numpy as np 
# import sklearn as sk
import matplotlib.pyplot as plt
import pandas as pd
import sympy as sp

In [10]:
def pmatrix(a, digit : int =3, T : bool =False):
    """Returns a LaTeX bmatrix
    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(np.round(a, digit)).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{pmatrix}']
    if not T:
        rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    else:
        rv += ['  ' + '\\\\ '.join(l.split()) for l in lines]
    rv +=  [r'\end{pmatrix}']
    return '\n'.join(rv)

In [11]:
# Данные для x1, x2, y из Таблицы 1
x1 = np.array([-1.0, -0.8, -0.6, -0.4, -0.2, 0.0, 0.2, 0.4, 0.8, 1.0])
x2 = np.array([1.0, -0.8, -0.2, -1.0, -0.6, 0.2, 0.6, 0.0, -0.4, 0.4])
y = np.array([4.037, -0.010, -2.304, -0.237, -2.104, -2.871, -1.673, -2.082, 1.368, 2.166])

# Данные для y_pi из Таблицы 1 и Таблицы 2
y_pi = np.array([
    -1.643, -1.730, -1.824, -1.757, -1.704, -1.671, -1.673, -1.802, -1.472, -1.594,
    -1.829, -1.595, -1.767, -1.704, -1.884, -1.636, -1.539, -1.624, -1.549, -1.604
])

In [13]:
F = np.array([[1 for _ in range(10)],
    x1, 
    x2, 
    x1**2,
    x1*x2,
    x2**2
])

In [14]:
F.T # Матрица регрессоров

array([[ 1.  , -1.  ,  1.  ,  1.  , -1.  ,  1.  ],
       [ 1.  , -0.8 , -0.8 ,  0.64,  0.64,  0.64],
       [ 1.  , -0.6 , -0.2 ,  0.36,  0.12,  0.04],
       [ 1.  , -0.4 , -1.  ,  0.16,  0.4 ,  1.  ],
       [ 1.  , -0.2 , -0.6 ,  0.04,  0.12,  0.36],
       [ 1.  ,  0.  ,  0.2 ,  0.  ,  0.  ,  0.04],
       [ 1.  ,  0.2 ,  0.6 ,  0.04,  0.12,  0.36],
       [ 1.  ,  0.4 ,  0.  ,  0.16,  0.  ,  0.  ],
       [ 1.  ,  0.8 , -0.4 ,  0.64, -0.32,  0.16],
       [ 1.  ,  1.  ,  0.4 ,  1.  ,  0.4 ,  0.16]])

In [16]:
print("F = ", pmatrix(F.T))
print("y = ", pmatrix(y, T=True))

F =  \begin{pmatrix}
  1. & -1. & 1. & 1. & -1. & 1.\\
  1. & -0.8 & -0.8 & 0.64 & 0.64 & 0.64\\
  1. & -0.6 & -0.2 & 0.36 & 0.12 & 0.04\\
  1. & -0.4 & -1. & 0.16 & 0.4 & 1.\\
  1. & -0.2 & -0.6 & 0.04 & 0.12 & 0.36\\
  1. & 0. & 0.2 & 0. & 0. & 0.04\\
  1. & 0.2 & 0.6 & 0.04 & 0.12 & 0.36\\
  1. & 0.4 & 0. & 0.16 & 0. & 0.\\
  1. & 0.8 & -0.4 & 0.64 & -0.32 & 0.16\\
  1. & 1. & 0.4 & 1. & 0.4 & 0.16\\
\end{pmatrix}
y =  \begin{pmatrix}
  4.037\\ -0.01\\ -2.304\\ -0.237\\ -2.104\\ -2.871\\ -1.673\\ -2.082\\ 1.368\\ 2.166
\end{pmatrix}


In [25]:
vrn = F @ y 
print(pmatrix(vrn, T=True)) # вектор системы нормальных уравнений
vrn

\begin{pmatrix}
  -3.71\\ -0.038\\ 4.746\\ 5.721\\ -4.439\\ 2.792
\end{pmatrix}


array([-3.71   , -0.038  ,  4.7464 ,  5.72056, -4.43928,  2.79232])

In [22]:
G = F @ F.T
print("F^T F = ", pmatrix(G)) # информационная матрица

F^T F =  \begin{pmatrix}
  10. & -0.6 & -0.8 & 4.04 & 0.48 & 3.76\\
  -0.6 & 4.04 & 0.48 & -0.216 & 0.4 & -1.648\\
  -0.8 & 0.48 & 3.76 & 0.4 & -1.648 & -0.512\\
  4.04 & -0.216 & 0.4 & 3.003 & -0.278 & 1.875\\
  0.48 & 0.4 & -1.648 & -0.278 & 1.875 & -0.086\\
  3.76 & -1.648 & -0.512 & 1.875 & -0.086 & 2.723\\
\end{pmatrix}


In [23]:
C = np.linalg.inv(F@F.T)
print("(F^T F) ^{-1} = ", pmatrix(np.round(C, 3))) # матрица дисперсий-ковариаций

(F^T F) ^{-1} =  \begin{pmatrix}
  0.329 & -0.096 & 0.018 & -0.248 & -0.1 & -0.341\\
  -0.096 & 0.441 & -0.039 & -0.152 & -0.103 & 0.493\\
  0.018 & -0.039 & 0.504 & -0.161 & 0.43 & 0.171\\
  -0.248 & -0.152 & -0.161 & 0.957 & 0.076 & -0.436\\
  -0.1 & -0.103 & 0.43 & 0.076 & 0.977 & 0.135\\
  -0.341 & 0.493 & 0.171 & -0.436 & 0.135 & 1.473\\
\end{pmatrix}


In [24]:
b = C @ vrn
print(np.round(b, 3)) # вектор оценок регрессионых
# коэффициентов без учета заданных линейных ограничений
print("b=", pmatrix(b, T=True))

[-3.059  1.123 -0.03   4.08  -1.103  3.078]
b= \begin{pmatrix}
  -3.059\\ 1.123\\ -0.03\\ 4.08\\ -1.103\\ 3.078
\end{pmatrix}


In [26]:
def lin_model(b):
    return np.round(b[0] + b[1] * x1 + b[2] * x2 + b[3] * x1**2 + b[4] * x1*x2 + b[5] * x2**2, 3)

In [38]:
y_p_mean = y_pi.mean()
print(y_p_mean)

-1.55995


In [43]:
# находим оценку дисперсии
s_pow = np.sum((y_pi - y_p_mean)**2) / 19
print("Оценка дисперсии:", round(s_pow, 5))

Оценка дисперсии: 0.00763


In [29]:
std = np.round(np.sum((y - lin_model(b))**2) / (10 - 6), 3)
print(std)

0.008


In [71]:
print(pmatrix(np.round(vrn.T, 3)))

\begin{pmatrix}
  -33.693 & 16.339 & 13.963 & -14.136 & -11.865 & -18.891\\
\end{pmatrix}


In [63]:
print(pmatrix(np.array(y).T))

\begin{pmatrix}
  -6.805 & -7.433 & -2.08 & -7.106 & -3.465 & -3.103 & -2.177 & -1.333 & 0.091 & -0.282\\
\end{pmatrix}


In [84]:
sigma = np.round(sum(std) / 4, 3)

In [28]:
df1 = pd.DataFrame({'k': [x for x in range(1, 11)],
               'y_k': y, 
                '\\hat{y_k}': lin_model(b),
                'y-y_k': np.round((y - lin_model(b))**2, 3) })

df_text = pd.concat([df1, pd.DataFrame(df1[["y-y_k"]].sum()).T]).fillna('')
print(df_text.to_latex(float_format="%.3f", index=False).replace("\\\n", "\\ \hline\n"))

\begin{tabular}{lllr}
\toprule
k & y_k & \hat{y_k} & y-y_k \\ \hline
\midrule
1.000 & 4.037 & 4.049 & 0.000 \\ \hline
2.000 & -0.010 & -0.057 & 0.002 \\ \hline
3.000 & -2.304 & -2.267 & 0.001 \\ \hline
4.000 & -0.237 & -0.188 & 0.002 \\ \hline
5.000 & -2.104 & -2.126 & 0.000 \\ \hline
6.000 & -2.871 & -2.942 & 0.005 \\ \hline
7.000 & -1.673 & -1.713 & 0.002 \\ \hline
8.000 & -2.082 & -1.957 & 0.016 \\ \hline
9.000 & 1.368 & 1.308 & 0.004 \\ \hline
10.000 & 2.166 & 2.184 & 0.000 \\ \hline
 &  &  & 0.032 \\ \hline
\bottomrule
\end{tabular}



In [35]:
y_over = y_pi.mean()
print(y_over)

-1.68005


In [36]:
df2 = pd.DataFrame({'k': [x for x in range(1, 21)],
                    "y_{pi}": y_pi,
                    '(y_{pi} - y_over)^2': (y_pi-y_over)**2, 
                 })

list_keys = df2.keys()
df2_text = pd.concat([df2, pd.DataFrame(df2[list_keys[1:]].sum()).T]).fillna('')

In [37]:
print(df2_text.to_latex(float_format="%.3f", index=False).replace("\\\n", "\\ \hline\n"))

\begin{tabular}{lrr}
\toprule
k & y_{pi} & (y_{pi} - y_over)^2 \\ \hline
\midrule
1.000 & -1.643 & 0.001 \\ \hline
2.000 & -1.730 & 0.002 \\ \hline
3.000 & -1.824 & 0.021 \\ \hline
4.000 & -1.757 & 0.006 \\ \hline
5.000 & -1.704 & 0.001 \\ \hline
6.000 & -1.671 & 0.000 \\ \hline
7.000 & -1.673 & 0.000 \\ \hline
8.000 & -1.802 & 0.015 \\ \hline
9.000 & -1.472 & 0.043 \\ \hline
10.000 & -1.594 & 0.007 \\ \hline
11.000 & -1.829 & 0.022 \\ \hline
12.000 & -1.595 & 0.007 \\ \hline
13.000 & -1.767 & 0.008 \\ \hline
14.000 & -1.704 & 0.001 \\ \hline
15.000 & -1.884 & 0.042 \\ \hline
16.000 & -1.636 & 0.002 \\ \hline
17.000 & -1.539 & 0.020 \\ \hline
18.000 & -1.624 & 0.003 \\ \hline
19.000 & -1.549 & 0.017 \\ \hline
20.000 & -1.604 & 0.006 \\ \hline
 & -33.601 & 0.224 \\ \hline
\bottomrule
\end{tabular}

