In [1]:
import numpy as np 
# import sklearn as sk
import matplotlib.pyplot as plt
import pandas as pd
import sympy as sp

In [2]:
def pmatrix(a, digit : int =3, T : bool =False):
    """Returns a LaTeX bmatrix
    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(np.round(a, digit)).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{pmatrix}']
    if not T:
        rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    else:
        rv += ['  ' + '\\\\ '.join(l.split()) for l in lines]
    rv +=  [r'\end{pmatrix}']
    return '\n'.join(rv)

In [3]:
# Данные для x1, x2, y из Таблицы 1
x1 = np.array([-1.0, -0.8, -0.6, -0.4, -0.2, 0.0, 0.2, 0.4, 0.8, 1.0])
x2 = np.array([0.4, -0.8, -0.2, -1.0, -0.6, 1.0, 0.6, 0.0, -0.4, 0.2])
y = np.array([1.891, 0.060, 0.004, -0.821, -1.544, 4.183, 1.376, -1.808, -3.703, -2.048])

# Данные для y_pi из Таблицы 1 и Таблицы 2
y_pi = np.array([
    -1.029, -0.860, -0.596, -0.821, -0.784, -0.617, -0.664, -0.808, -0.703, -0.728,
    -0.773, -0.924, -0.879, -0.720, -0.971, -0.832, -0.860, -0.843, -0.760, -0.827
])

In [4]:
F = np.array([[1 for _ in range(10)],
    x1, 
    x2, 
    x1**2,
    x1*x2,
    x2**2
])

In [6]:
F.T # Матрица регрессоров

array([[ 1.  , -1.  ,  0.4 ,  1.  , -0.4 ,  0.16],
       [ 1.  , -0.8 , -0.8 ,  0.64,  0.64,  0.64],
       [ 1.  , -0.6 , -0.2 ,  0.36,  0.12,  0.04],
       [ 1.  , -0.4 , -1.  ,  0.16,  0.4 ,  1.  ],
       [ 1.  , -0.2 , -0.6 ,  0.04,  0.12,  0.36],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ],
       [ 1.  ,  0.2 ,  0.6 ,  0.04,  0.12,  0.36],
       [ 1.  ,  0.4 ,  0.  ,  0.16,  0.  ,  0.  ],
       [ 1.  ,  0.8 , -0.4 ,  0.64, -0.32,  0.16],
       [ 1.  ,  1.  ,  0.2 ,  1.  ,  0.2 ,  0.04]])

In [9]:
print("F = ", pmatrix(F.T))
print("y = ", pmatrix(y, 4, T=False))

F =  \begin{pmatrix}
  1. & -1. & 0.4 & 1. & -0.4 & 0.16\\
  1. & -0.8 & -0.8 & 0.64 & 0.64 & 0.64\\
  1. & -0.6 & -0.2 & 0.36 & 0.12 & 0.04\\
  1. & -0.4 & -1. & 0.16 & 0.4 & 1.\\
  1. & -0.2 & -0.6 & 0.04 & 0.12 & 0.36\\
  1. & 0. & 1. & 0. & 0. & 1.\\
  1. & 0.2 & 0.6 & 0.04 & 0.12 & 0.36\\
  1. & 0.4 & 0. & 0.16 & 0. & 0.\\
  1. & 0.8 & -0.4 & 0.64 & -0.32 & 0.16\\
  1. & 1. & 0.2 & 1. & 0.2 & 0.04\\
\end{pmatrix}
y =  \begin{pmatrix}
  1.891e+00 & 6.000e-02 & 4.000e-03 & -8.210e-01 & -1.544e+00 & 4.183e+00\\
  1.376e+00 & -1.808e+00 & -3.703e+00 & -2.048e+00\\
\end{pmatrix}


In [14]:
print(*y, sep=" \\\\")

1.891 \\0.06 \\0.004 \\-0.821 \\-1.544 \\4.183 \\1.376 \\-1.808 \\-3.703 \\-2.048


In [20]:
vrn = F @ y 
print(pmatrix(vrn, T=True)) # вектор системы нормальных уравнений
vrn

\begin{pmatrix}
  -2.41\\ -6.763\\ 8.535\\ -2.914\\ -0.291\\ 2.968
\end{pmatrix}


array([-2.41   , -6.7626 ,  8.5352 , -2.91444, -0.29072,  2.96824])

In [16]:
G = F @ F.T
print("F^T F = ", pmatrix(G)) # информационная матрица

F^T F =  \begin{pmatrix}
  10. & -0.6 & -0.8 & 4.04 & 0.88 & 3.76\\
  -0.6 & 4.04 & 0.88 & -0.216 & -0.4 & -0.928\\
  -0.8 & 0.88 & 3.76 & -0.4 & -0.928 & -0.512\\
  4.04 & -0.216 & -0.4 & 3.003 & 0.122 & 0.915\\
  0.88 & -0.4 & -0.928 & 0.122 & 0.915 & 0.794\\
  3.76 & -0.928 & -0.512 & 0.915 & 0.794 & 2.723\\
\end{pmatrix}


In [18]:
C = np.linalg.inv(F@F.T)
print("(F^T F) ^{-1} = ", pmatrix(np.round(C, 3))) # матрица дисперсий-ковариаций

(F^T F) ^{-1} =  \begin{pmatrix}
  0.539 & -0.084 & 0.005 & -0.55 & 0.043 & -0.6\\
  -0.084 & 0.292 & -0.059 & 0.07 & -0.024 & 0.188\\
  0.005 & -0.059 & 0.38 & 0.053 & 0.434 & -0.1\\
  -0.55 & 0.07 & 0.053 & 0.945 & 0.1 & 0.446\\
  0.043 & -0.024 & 0.434 & 0.1 & 1.987 & -0.599\\
  -0.6 & 0.188 & -0.1 & 0.446 & -0.599 & 1.266\\
\end{pmatrix}


In [21]:
b = C @ vrn
print(np.round(b, 3)) # вектор оценок регрессионых
# коэффициентов без учета заданных линейных ограничений
print("b=", pmatrix(b, T=True))

[-0.883 -1.919  3.057 -0.155  1.116  1.956]
b= \begin{pmatrix}
  -0.883\\ -1.919\\ 3.057\\ -0.155\\ 1.116\\ 1.956
\end{pmatrix}


In [22]:
def lin_model(b):
    return np.round(b[0] + b[1] * x1 + b[2] * x2 + b[3] * x1**2 + b[4] * x1*x2 + b[5] * x2**2, 3)

In [25]:
y_p_mean = y_pi.mean()
print(np.round(y_p_mean, 4))

-0.7999


In [26]:
# находим оценку дисперсии
s_pow = np.sum((y_pi - y_p_mean)**2) / 19
print("Оценка дисперсии:", round(s_pow, 5))

Оценка дисперсии: 0.0122


In [29]:
std = np.round(np.sum((y - lin_model(b))**2) / (10 - 6), 3)
print(std)

0.008


In [27]:
print(pmatrix(np.round(vrn.T, 3)))

\begin{pmatrix}
  -2.41 & -6.763 & 8.535 & -2.914 & -0.291 & 2.968\\
\end{pmatrix}


In [28]:
vrn

array([-2.41   , -6.7626 ,  8.5352 , -2.91444, -0.29072,  2.96824])

In [63]:
print(pmatrix(np.array(y).T))

\begin{pmatrix}
  -6.805 & -7.433 & -2.08 & -7.106 & -3.465 & -3.103 & -2.177 & -1.333 & 0.091 & -0.282\\
\end{pmatrix}


In [84]:
sigma = np.round(sum(std) / 4, 3)

In [28]:
df1 = pd.DataFrame({'k': [x for x in range(1, 11)],
               'y_k': y, 
                '\\hat{y_k}': lin_model(b),
                'y-y_k': np.round((y - lin_model(b))**2, 3) })

df_text = pd.concat([df1, pd.DataFrame(df1[["y-y_k"]].sum()).T]).fillna('')
print(df_text.to_latex(float_format="%.3f", index=False).replace("\\\n", "\\ \hline\n"))

\begin{tabular}{lllr}
\toprule
k & y_k & \hat{y_k} & y-y_k \\ \hline
\midrule
1.000 & 4.037 & 4.049 & 0.000 \\ \hline
2.000 & -0.010 & -0.057 & 0.002 \\ \hline
3.000 & -2.304 & -2.267 & 0.001 \\ \hline
4.000 & -0.237 & -0.188 & 0.002 \\ \hline
5.000 & -2.104 & -2.126 & 0.000 \\ \hline
6.000 & -2.871 & -2.942 & 0.005 \\ \hline
7.000 & -1.673 & -1.713 & 0.002 \\ \hline
8.000 & -2.082 & -1.957 & 0.016 \\ \hline
9.000 & 1.368 & 1.308 & 0.004 \\ \hline
10.000 & 2.166 & 2.184 & 0.000 \\ \hline
 &  &  & 0.032 \\ \hline
\bottomrule
\end{tabular}



In [31]:
y_over = y_pi.mean()
print(y_over)

-0.7999499999999999


In [35]:
df2 = pd.DataFrame({'k': [x for x in range(1, 21)],
                    "y_{pi}": y_pi,
                    '(y_{pi} - y_over)^2': (y_pi-y_over)**2, 
                 })

list_keys = df2.keys()
df2_text = pd.concat([df2, pd.DataFrame(df2[list_keys[1:]].sum()).T]).fillna('')

In [36]:
print(df2_text.to_latex(float_format="%.3f", index=False).replace("\\\n", "\\ \hline\n"))

\begin{tabular}{lrr}
\toprule
k & y_{pi} & (y_{pi} - y_over)^2 \\ \hline
\midrule
1.000 & -1.029 & 0.052 \\ \hline
2.000 & -0.860 & 0.004 \\ \hline
3.000 & -0.596 & 0.042 \\ \hline
4.000 & -0.821 & 0.000 \\ \hline
5.000 & -0.784 & 0.000 \\ \hline
6.000 & -0.617 & 0.033 \\ \hline
7.000 & -0.664 & 0.018 \\ \hline
8.000 & -0.808 & 0.000 \\ \hline
9.000 & -0.703 & 0.009 \\ \hline
10.000 & -0.728 & 0.005 \\ \hline
11.000 & -0.773 & 0.001 \\ \hline
12.000 & -0.924 & 0.015 \\ \hline
13.000 & -0.879 & 0.006 \\ \hline
14.000 & -0.720 & 0.006 \\ \hline
15.000 & -0.971 & 0.029 \\ \hline
16.000 & -0.832 & 0.001 \\ \hline
17.000 & -0.860 & 0.004 \\ \hline
18.000 & -0.843 & 0.002 \\ \hline
19.000 & -0.760 & 0.002 \\ \hline
20.000 & -0.827 & 0.001 \\ \hline
 & -15.999 & 0.232 \\ \hline
\bottomrule
\end{tabular}



In [34]:
s = np.round(np.sum((y_pi - y_over)**2) / 19, 3)
print(s)

0.012


In [39]:
print(np.round(s**0.5, 3))

0.11


array([-0.88263549, -1.91924759,  3.05665241, -0.15538191,  1.11581275,
        1.95637127])

In [48]:
C = np.round(C, 3)
for i in range(len(C)):
    print(f'\n$c_{{{i+1}{i+1}}} = {C[i][i]}$')
    t = np.round(np.abs(b[i]) / (s**0.5 * np.sqrt(C[i][i])))
    t_kp = 2.09
    print(f"$t_{i+1} = \\dfrac{{|{np.round(b[i], 3)}|}}{{ {np.round(s**0.5, 3)} \\sqrt{{  {C[i][i]} }}}} = {t}$")
    if t>t_kp:
        print(f"\n \\\\ $t_{i+1} > t_{{кр}}$, значит что коэффициент $b_{i+1} = {C[i][i]} $ \\textbf{{Значим}}")
    else:
        print(f"\n \\\\ $t_{i+1} > t_{{кр}}$, значит что коэффициент $b_{i+1} = {C[i][i]} $ \\textbf{{Не значим}}")


$c_{11} = 0.539$
$t_1 = \dfrac{|-0.883|}{ 0.11 \sqrt{  0.539 }} = 11.0$

 \\ $t_1 > t_{кр}$, значит что коэффициент $b_1 = 0.539 $ \textbf{Значим}

$c_{22} = 0.292$
$t_2 = \dfrac{|-1.919|}{ 0.11 \sqrt{  0.292 }} = 32.0$

 \\ $t_2 > t_{кр}$, значит что коэффициент $b_2 = 0.292 $ \textbf{Значим}

$c_{33} = 0.38$
$t_3 = \dfrac{|3.057|}{ 0.11 \sqrt{  0.38 }} = 45.0$

 \\ $t_3 > t_{кр}$, значит что коэффициент $b_3 = 0.38 $ \textbf{Значим}

$c_{44} = 0.945$
$t_4 = \dfrac{|-0.155|}{ 0.11 \sqrt{  0.945 }} = 1.0$

 \\ $t_4 > t_{кр}$, значит что коэффициент $b_4 = 0.945 $ \textbf{Не значим}

$c_{55} = 1.987$
$t_5 = \dfrac{|1.116|}{ 0.11 \sqrt{  1.987 }} = 7.0$

 \\ $t_5 > t_{кр}$, значит что коэффициент $b_5 = 1.987 $ \textbf{Значим}

$c_{66} = 1.266$
$t_6 = \dfrac{|1.956|}{ 0.11 \sqrt{  1.266 }} = 16.0$

 \\ $t_6 > t_{кр}$, значит что коэффициент $b_6 = 1.266 $ \textbf{Значим}


In [52]:
df2 = pd.DataFrame({'k': [x for x in range(1, 11)],
                    '$y_k$': y,
               '$(y_k - \\overline{y})^2$': (y-y_over)**2, 
               '$\\hat{y_k}$': lin_model(b),
                '$(\\hat{y_k} - \\overline{y})^2$': (lin_model(b)-y_over)**2,
       })

list_keys = df2.keys()
df2_text = pd.concat([df2, pd.DataFrame(df2[list_keys[1:]].sum()).T]).fillna('')
print(df2_text.to_latex(float_format="%.3f", index=False).replace("\\\n", "\\ \hline\n"))

\begin{tabular}{lrrrr}
\toprule
k & $y_k$ & $(y_k - \overline{y})^2$ & $\hat{y_k}$ & $(\hat{y_k} - \overline{y})^2$ \\ \hline
\midrule
1.000 & 1.891 & 7.241 & 1.971 & 7.678 \\ \hline
2.000 & 0.060 & 0.740 & 0.074 & 0.764 \\ \hline
3.000 & 0.004 & 0.646 & -0.186 & 0.377 \\ \hline
4.000 & -0.821 & 0.000 & -0.794 & 0.000 \\ \hline
5.000 & -1.544 & 0.554 & -1.501 & 0.491 \\ \hline
6.000 & 4.183 & 24.830 & 4.130 & 24.304 \\ \hline
7.000 & 1.376 & 4.735 & 1.399 & 4.835 \\ \hline
8.000 & -1.808 & 1.016 & -1.675 & 0.766 \\ \hline
9.000 & -3.703 & 8.428 & -3.784 & 8.905 \\ \hline
10.000 & -2.048 & 1.558 & -2.045 & 1.550 \\ \hline
 & -2.410 & 49.747 & -2.411 & 49.671 \\ \hline
\bottomrule
\end{tabular}



In [74]:
df2_sum = df2.sum(axis=0).to_list()
Q_r = df2_sum[2], df2_sum[4] 

print(Q_r[1] / Q_r[0])

print([Q_r[1] / 5])
print(Q_r[0] * (0.005) / 4)
print(9.93 / 0.062)

0.998461039693956
[9.934119624999997]
0.06218394628125
160.16129032258064
