In [72]:
import numpy as np 
import sklearn as sk
import matplotlib.pyplot as plt
import pandas as pd

In [62]:
x1 = np.array([-1, -.8, -.6, -.4, -.2, 0, 0.2, .4, .6, 1])
x2 = np.array([-.6, -.8, .2, -1, -.4, 1, .6, -.2, 0, .0])
y = np.array([-6.805, -7.433, -2.080, -7.106, -3.465, -3.103, -2.177, -1.333, 0.091, -0.282])

In [4]:
len(x) == len(x2) and len(x) == len(y)

True

In [9]:
F = np.array([[1 for _ in range(10)],
    x, 
    x2, 
    [x**2 for x in x1],
    [x1[i] * x2[i] for i in range(10)],
    [x**2 for x in x2]
])

In [11]:
F.T # Матрица регрессоров

array([[ 1.  , -1.  , -0.6 ,  1.  ,  0.6 ,  0.36],
       [ 1.  , -0.8 , -0.8 ,  0.64,  0.64,  0.64],
       [ 1.  , -0.6 ,  0.2 ,  0.36, -0.12,  0.04],
       [ 1.  , -0.4 , -1.  ,  0.16,  0.4 ,  1.  ],
       [ 1.  , -0.2 , -0.4 ,  0.04,  0.08,  0.16],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ],
       [ 1.  ,  0.2 ,  0.6 ,  0.04,  0.12,  0.36],
       [ 1.  ,  0.4 , -0.2 ,  0.16, -0.08,  0.04],
       [ 1.  ,  0.6 ,  0.  ,  0.36,  0.  ,  0.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ]])

In [65]:
vrn = F @ y 
print(vrn) # вектор системы нормальных уравнений
vrn

[-33.693    16.3388   13.9628  -14.13608 -11.86472 -18.89056]


array([-33.693  ,  16.3388 ,  13.9628 , -14.13608, -11.86472, -18.89056])

In [14]:
G = F @ F.T
print(G) # информационная матрица

[[10.     -0.8    -1.2     3.76    1.64    3.6   ]
 [-0.8     3.76    1.64   -0.512  -1.224  -1.24  ]
 [-1.2     1.64    3.6    -1.224  -1.24   -0.576 ]
 [ 3.76   -0.512  -1.224   2.7232  1.0256  0.9712]
 [ 1.64   -1.224  -1.24    1.0256  0.9712  1.0736]
 [ 3.6    -1.24   -0.576   0.9712  1.0736  2.6976]]


In [17]:
C = np.linalg.inv(F@F.T)
print(np.round(C, 3)) # матрица дисперсий-ковариаций

[[ 0.493 -0.01   0.087 -0.679  0.758 -0.701]
 [-0.01   0.55   0.021 -0.257  1.084 -0.068]
 [ 0.087  0.021  0.649 -0.198  1.433 -0.467]
 [-0.679 -0.257 -0.198  1.692 -2.442  1.108]
 [ 0.758  1.084  1.433 -2.442  8.538 -2.726]
 [-0.701 -0.068 -0.467  1.108 -2.726  1.861]]


In [21]:
b = C @ vrn
print(np.round(b, 3)) # вектор оценок регрессионых
# коэффициентов без учета заданных линейных ограничений

[-1.71   1.68   1.087  0.032 -3.101 -2.493]


In [30]:
def lin_model(b):
    return np.round(b[0] + b[1] * x1 + b[2] * x2 + b[3] * x1**2 + b[4] * x1*x2 + b[5] * x2**2, 3)

In [51]:
std = np.round((y - lin_model(b))**2, 3)

In [55]:
def pmatrix(a):
    """Returns a LaTeX bmatrix
    :a: numpy array
    :returns: LaTeX bmatrix as a string
    """
    if len(a.shape) > 2:
        raise ValueError('bmatrix can at most display two dimensions')
    lines = str(a).replace('[', '').replace(']', '').splitlines()
    rv = [r'\begin{pmatrix}']
    rv += ['  ' + ' & '.join(l.split()) + r'\\' for l in lines]
    rv +=  [r'\end{pmatrix}']
    return '\n'.join(rv)

In [71]:
print(pmatrix(np.round(vrn.T, 3)))

\begin{pmatrix}
  -33.693 & 16.339 & 13.963 & -14.136 & -11.865 & -18.891\\
\end{pmatrix}


In [63]:
print(pmatrix(np.array(y).T))

\begin{pmatrix}
  -6.805 & -7.433 & -2.08 & -7.106 & -3.465 & -3.103 & -2.177 & -1.333 & 0.091 & -0.282\\
\end{pmatrix}


In [84]:
sigma = np.round(sum(std) / 4, 3)

In [80]:
print(pd.DataFrame({'k': [x for x in range(1, 11)],
               'y_k': y, 
                '\\hat{y_k}': lin_model(b),
                'y-y_k': std}))

\begin{tabular}{lrrrr}
\toprule
 & k & y_k & \hat{y_k} & y-y_k \\
\midrule
0 & 1 & -6.805000 & -6.769000 & 0.001000 \\
1 & 2 & -7.433000 & -7.484000 & 0.003000 \\
2 & 3 & -2.080000 & -2.217000 & 0.019000 \\
3 & 4 & -7.106000 & -7.198000 & 0.008000 \\
4 & 5 & -3.465000 & -3.127000 & 0.114000 \\
5 & 6 & -3.103000 & -3.117000 & 0.000000 \\
6 & 7 & -2.177000 & -1.991000 & 0.035000 \\
7 & 8 & -1.333000 & -1.102000 & 0.053000 \\
8 & 9 & 0.091000 & -0.691000 & 0.612000 \\
9 & 10 & -0.282000 & 0.002000 & 0.081000 \\
\bottomrule
\end{tabular}



In [87]:
print(C * sigma) # Матрица дисперсий и ковариаций

print(pmatrix(np.round(C * sigma, 3)))

[[ 0.11390147 -0.00230275  0.02008732 -0.15684988  0.17512253 -0.16199932]
 [-0.00230275  0.12704414  0.00487683 -0.05942778  0.25038637 -0.01574172]
 [ 0.02008732  0.00487683  0.14989751 -0.04566171  0.3310958  -0.10788995]
 [-0.15684988 -0.05942778 -0.04566171  0.39082878 -0.56409748  0.25604616]
 [ 0.17512253  0.25038637  0.3310958  -0.56409748  1.97228106 -0.62975989]
 [-0.16199932 -0.01574172 -0.10788995  0.25604616 -0.62975989  0.43000126]]
\begin{pmatrix}
  0.114 & -0.002 & 0.02 & -0.157 & 0.175 & -0.162\\
  -0.002 & 0.127 & 0.005 & -0.059 & 0.25 & -0.016\\
  0.02 & 0.005 & 0.15 & -0.046 & 0.331 & -0.108\\
  -0.157 & -0.059 & -0.046 & 0.391 & -0.564 & 0.256\\
  0.175 & 0.25 & 0.331 & -0.564 & 1.972 & -0.63\\
  -0.162 & -0.016 & -0.108 & 0.256 & -0.63 & 0.43\\
\end{pmatrix}


In [159]:
A = np.array([[-1, 2, 7, 5, 1, 1],
    [9, -4, 8, -3, 6, 2],
     [3, 1, -1, 1, -3, 3]])
d = np.array([[12], [-49], [2]]).T

In [91]:
print(pmatrix(A))

\begin{pmatrix}
  -1 & 2 & 7 & 5 & 1 & 1\\
  9 & -4 & 8 & -3 & 6 & 2\\
  3 & 1 & -1 & 1 & -3 & 3\\
\end{pmatrix}


In [162]:
print(A.T.shape, b[np.newaxis, :].T .shape)

(3, 6) (6, 1)


In [160]:
dAb = np.round(d - A @ b, 3)
print(pmatrix(dAb))

\begin{pmatrix}
  4.754 & -11.894 & 4.683\\
\end{pmatrix}


In [145]:
test = np.array([[-1.71043618],  [1.68013452],  [1.08696328],  [0.03210172], [-3.1007982] ,
       [-2.49321335]])

dAb = np.round(d -A @ test)

In [151]:
np.array(b).T

array([-1.71043618,  1.68013452,  1.08696328,  0.03210172, -3.1007982 ,
       -2.49321335])

In [171]:
lol = np.round(C @ A.T, 3)
kek = np.round(A @ lol, 3)
fff = np.round(np.linalg.inv(kek), 3)
aaa = np.round(lol @ fff, 3)

In [172]:
print(pmatrix(lol))
print(pmatrix(kek))
print(pmatrix(fff))
print(pmatrix(aaa))

\begin{pmatrix}
  -3.243 & 10.356 & -3.675\\
  0.987 & 5.018 & -3.215\\
  4.476 & 14.148 & -6.266\\
  5.907 & -24.174 & 10.247\\
  5.045 & 67.055 & -34.31\\
  1.973 & -25.735 & 13.167\\
\end{pmatrix}
\begin{pmatrix}
  73.102 & 19.166 & -16.525\\
  19.168 & 609.698 & -280.61\\
  -16.527 & -280.606 & 144.704\\
\end{pmatrix}
\begin{pmatrix}
  0.015 & 0.003 & 0.007\\
  0.003 & 0.016 & 0.031\\
  0.007 & 0.031 & 0.068\\
\end{pmatrix}
\begin{pmatrix}
  -0.043 & 0.042 & 0.048\\
  0.007 & -0.016 & -0.056\\
  0.066 & 0.046 & 0.044\\
  0.088 & -0.051 & -0.011\\
  0.037 & 0.024 & -0.219\\
  0.045 & 0.002 & 0.111\\
\end{pmatrix}


In [210]:
b_new = np.round(b[np.newaxis, :].T + aaa @ dAb.T, 3)
print(pmatrix(b_new))

\begin{pmatrix}
  -2.19\\
  1.641\\
  1.06\\
  1.006\\
  -4.236\\
  -1.783\\
\end{pmatrix}


In [213]:
lin_model(b_new)

array([-6.644, -7.559, -2.163, -7.223, -3.526, -2.913, -2.336, -1.317,
       -0.843,  0.457])

In [214]:
C

array([[ 0.49307997, -0.00996862,  0.0869581 , -0.67900381,  0.75810618,
        -0.70129575],
       [-0.00996862,  0.54997463,  0.02111181, -0.2572631 ,  1.08392367,
        -0.06814596],
       [ 0.0869581 ,  0.02111181,  0.64890697, -0.19766975,  1.43331515,
        -0.46705604],
       [-0.67900381, -0.2572631 , -0.19766975,  1.69189949, -2.44198045,
         1.10842495],
       [ 0.75810618,  1.08392367,  1.43331515, -2.44198045,  8.53801323,
        -2.72623331],
       [-0.70129575, -0.06814596, -0.46705604,  1.10842495, -2.72623331,
         1.86147732]])

In [231]:
F.T

array([[ 1.  , -1.  , -0.6 ,  1.  ,  0.6 ,  0.36],
       [ 1.  , -0.8 , -0.8 ,  0.64,  0.64,  0.64],
       [ 1.  , -0.6 ,  0.2 ,  0.36, -0.12,  0.04],
       [ 1.  , -0.4 , -1.  ,  0.16,  0.4 ,  1.  ],
       [ 1.  , -0.2 , -0.4 ,  0.04,  0.08,  0.16],
       [ 1.  ,  0.  ,  1.  ,  0.  ,  0.  ,  1.  ],
       [ 1.  ,  0.2 ,  0.6 ,  0.04,  0.12,  0.36],
       [ 1.  ,  0.4 , -0.2 ,  0.16, -0.08,  0.04],
       [ 1.  ,  0.6 ,  0.  ,  0.36,  0.  ,  0.  ],
       [ 1.  ,  1.  ,  0.  ,  1.  ,  0.  ,  0.  ]])

In [198]:
aaa.shape, dAb.T.shape

((6, 3), (3, 1))

In [251]:
L = np.eye(6) - aaa @ A
print(pmatrix(L))

\begin{pmatrix}
  0.435 & 0.206 & 0.013 & 0.293 & -0.065 & -0.185\\
  0.319 & 0.978 & 0.023 & -0.027 & -0.079 & 0.193\\
  -0.48 & 0.008 & 0.214 & -0.236 & -0.21 & -0.29\\
  0.58 & -0.369 & -0.219 & 0.418 & 0.185 & 0.047\\
  0.478 & 0.241 & -0.67 & 0.106 & 0.162 & 0.572\\
  -0.306 & -0.193 & -0.22 & -0.33 & 0.276 & 0.618\\
\end{pmatrix}


In [241]:
Q = y[np.newaxis, :].T- F.T @ b_new

In [249]:
print(pmatrix(Q))

\begin{pmatrix}
  -0.16052\\
  0.12612\\
  0.08344\\
  0.11684\\
  0.06112\\
  -0.19\\
  0.15876\\
  -0.01592\\
  0.93424\\
  -0.739\\
\end{pmatrix}


In [243]:
sum(Q**2)

array([1.54650596])

In [253]:
sigma_new = np.round(sum(Q**2) / 7, 3)

In [247]:
print(pmatrix(np.eye(6)))

\begin{pmatrix}
  1. & 0. & 0. & 0. & 0. & 0.\\
  0. & 1. & 0. & 0. & 0. & 0.\\
  0. & 0. & 1. & 0. & 0. & 0.\\
  0. & 0. & 0. & 1. & 0. & 0.\\
  0. & 0. & 0. & 0. & 1. & 0.\\
  0. & 0. & 0. & 0. & 0. & 1.\\
\end{pmatrix}


In [255]:
V_new = L @ C * sigma_new

In [258]:
print(pmatrix(np.round(V_new, 3)))

\begin{pmatrix}
  0.021 & -0.005 & -0.003 & 0.022 & -0.043 & -0.037\\
  -0.006 & 0.098 & -0.03 & -0.025 & 0.044 & 0.054\\
  -0.003 & -0.029 & -0.005 & 0.016 & -0.105 & 0.002\\
  0.021 & -0.027 & 0.014 & 0.011 & 0.035 & -0.051\\
  -0.039 & 0.049 & -0.098 & 0.036 & -0.171 & 0.155\\
  -0.037 & 0.052 & -0. & -0.054 & 0.159 & 0.08\\
\end{pmatrix}
